### ISSUE TITLE
can not open the web page

### ISSUE THREAD

**Issue by joy1314** [basvandenberg/spiceweb#10]
I can not open the web page..
Forbidden

You don't have permission to access /spice/ on this server.

Apache/2.2.15 (Red Hat) Server at helix.ewi.tudelft.nl Port 80

**Comment by basvandenberg** [comment]
I already left the university over three years ago and have no access to the web application (I developed this software during my PhD there). This was not an easy web application to run (webserver on a normal server machine, but the feature computation and classification jobs where queued and executed on separate compute servers), so I guess that's why its not available anymore.

I will remove the link from the readme file. You could try to run the web application locally on your own machine, which is what I used to do while developing, but this is probably not that straightforward.
